remote_theme: pages-themes/minimal@v0.2.0
title: "Thegye Roleplay Community"
description: "The Thegye Roleplay Community hosts a geopolitical roleplay. This website hosts details and information about rules, applications, and more."
